### ISSUE TITLE
Compile error in Catena-mcciadk on ESP32

### ISSUE THREAD

**Issue by schenlap** [mcci-catena/Catena-mcciadk#22]
I get the following error
`WARNING: library brzo_i2c-master claims to run on esp8266 architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).
In file included from /home/xxx/Arduino/libraries/arduino-lorawan-master/src/lib/GetRegionString.cpp:19:0:
/home/xxx/Arduino/libraries/Catena-mcciadk-0.2.1/src/mcciadk_baselib.h: In function 'size_t McciAdkLib_BufferToUint32(const char*, size_t, unsigned int, uint32_t*, bool*)':
/home/xxx/Arduino/libraries/Catena-mcciadk-0.2.1/src/mcciadk_baselib.h:49:64: error: invalid conversion from 'uint32_t* {aka unsigned int*}' to 'long unsigned int*' [-fpermissive]
  return McciAdkLib_BufferToUlong(s, n, base, pulnum, pfOverflow);
                                                                ^
/home/xxx/Arduino/libraries/Catena-mcciadk-0.2.1/src/mcciadk_baselib.h:31:1: note:   initializing argument 4 of 'size_t McciAdkLib_BufferToUlong(const char*, size_t, unsigned int, long unsigned int*, bool*)'
 McciAdkLib_BufferToUlong(
 ^
In file included from /home/xxx/Arduino/libraries/arduino-lorawan-master/src/lib/arduino_lorawan_begin.cpp:20:0:
/home/xxx/Arduino/libraries/Catena-mcciadk-0.2.1/src/mcciadk_baselib.h: In function 'size_t McciAdkLib_BufferToUint32(const char*, size_t, unsigned int, uint32_t*, bool*)':
/home/xxx/Arduino/libraries/Catena-mcciadk-0.2.1/src/mcciadk_baselib.h:49:64: error: invalid conversion from 'uint32_t* {aka unsigned int*}' to 'long unsigned int*' [-fpermissive]
  return McciAdkLib_BufferToUlong(s, n, base, pulnum, pfOverflow);
                                                                ^
/home/xxx/Arduino/libraries/Catena-mcciadk-0.2.1/src/mcciadk_baselib.h:31:1: note:   initializing argument 4 of 'size_t McciAdkLib_BufferToUlong(const char*, size_t, unsigned int, long unsigned int*, bool*)'
 McciAdkLib_BufferToUlong(`

The documentations says that Catena-mcciadk 0.1.1 is needed, but on https://github.com/mcci-catena/Catena-mcciadk/releases there is no 0.1.1. Comiling does not work with 0.1.3 nor with master of Catena-mcciadk.
